---
openapi: 3.0.1
info:
  title: Desk booking API
  version: v1
components:
  securitySchemes:
    apiOauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:3000/oauth/authorize
          tokenUrl: http://localhost:3000/oauth/token
          scopes: {}
paths:
  "/users":
    get:
      summary: list profiles
      responses:
        '200':
          description: successful
    post:
      summary: create profile
      responses:
        '200':
          description: successful
  "/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show profile
      responses:
        '200':
          description: successful
    patch:
      summary: update profile
      responses:
        '200':
          description: successful
    put:
      summary: update profile
      responses:
        '200':
          description: successful
    delete:
      summary: delete profile
      responses:
        '200':
          description: successful
servers:
- url: "/"
